FROM python:3.12-slim

WORKDIR /app

COPY requirements_frontend.txt .

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements_frontend.txt

COPY app.py .
COPY frontend/ ./frontend/
COPY common/ ./common/

RUN useradd -m -r appuser && chown -R appuser:appuser /app

EXPOSE 8000

USER appuser

CMD ["gunicorn", "--bind=0.0.0.0:8000", "--timeout=600", "--workers=2", "--preload", "app:app"]